/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author entorno
 */
public class Articulos extends javax.swing.JFrame {

    static public ResultSet r;

    /**
     * Creates new form Articulos
     *
     * @throws java.sql.SQLException
     */
    public Articulos() throws SQLException {
        initComponents();
        String url = "jdbc:mysql://localhost:3306/sergiooyono";
        String user = "root";
        String pass = "";
        Connection connection = DriverManager.getConnection(url, user, pass);

        Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String query = "select* from articulos";
        r = s.executeQuery(query);
        r.first();
        COD_ARTICULO.setText(r.getString("COD_ARTICULO"));
        ARTICULO.setText(r.getString("ARTICULO"));
        FABRICANTE.setText(r.getString("FABRICANTE"));
        PESO.setText(r.getString("PESO"));
        CATEGORIA.setText(r.getString("CATEGORIA"));
        PRECIO_VENTA.setText(r.getString("PRECIO_VENTA"));
        PRECIO_COSTE.setText(r.getString("PRECIO_COSTE"));
        EXISTENCIAS.setText(r.getString("EXISTENCIAS"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        COD_ARTICULO = new javax.swing.JTextField();
        ARTICULO = new javax.swing.JTextField();
        FABRICANTE = new javax.swing.JTextField();
        PESO = new javax.swing.JTextField();
        CATEGORIA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PRECIO_VENTA = new javax.swing.JTextField();
        PRECIO_COSTE = new javax.swing.JTextField();
        EXISTENCIAS = new javax.swing.JTextField();
        PRIMERO = new javax.swing.JButton();
        ANTERIOR = new javax.swing.JButton();
        SIGUIENTE = new javax.swing.JButton();
        ULTIMO = new javax.swing.JButton();
        EDITAR = new javax.swing.JButton();
        NUEVO = new javax.swing.JButton();
        CONFIRMAR = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        COD_ARTICULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COD_ARTICULOActionPerformed(evt);
            }
        });

        PESO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PESOActionPerformed(evt);
            }
        });

        jLabel1.setText("COD_ARTICULO");

        jLabel2.setText("ARTICULO");

        jLabel3.setText("FABRICANTE");

        jLabel4.setText("PESO");

        jLabel5.setText("CATEGORIA");

        jLabel6.setText("PRECIO_VENTA");

        jLabel7.setText("PRECIO_COSTE");

        jLabel8.setText("EXISTENCIAS");

        EXISTENCIAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXISTENCIASActionPerformed(evt);
            }
        });

        PRIMERO.setText("PRIMERO");
        PRIMERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRIMEROActionPerformed(evt);
            }
        });

        ANTERIOR.setText("ANTERIOR");
        ANTERIOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANTERIORActionPerformed(evt);
            }
        });

        SIGUIENTE.setText("SIGUIENTE");
        SIGUIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIGUIENTEActionPerformed(evt);
            }
        });

        ULTIMO.setText("ULTIMO");
        ULTIMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ULTIMOActionPerformed(evt);
            }
        });

        EDITAR.setText("EDITAR");
        EDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITARActionPerformed(evt);
            }
        });

        NUEVO.setText("NUEVO");
        NUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVOActionPerformed(evt);
            }
        });

        CONFIRMAR.setText("CONFIRMAR");
        CONFIRMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONFIRMARActionPerformed(evt);
            }
        });

        CANCELAR.setText("CANCELAR");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PRECIO_VENTA))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(COD_ARTICULO, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CATEGORIA)))
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PESO, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ARTICULO, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EXISTENCIAS))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PRECIO_COSTE, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FABRICANTE, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PRIMERO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ANTERIOR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SIGUIENTE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ULTIMO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EDITAR)
                        .addGap(18, 18, 18)
                        .addComponent(NUEVO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CONFIRMAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CANCELAR)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(COD_ARTICULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ARTICULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FABRICANTE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(PESO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CATEGORIA, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PRECIO_VENTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PRECIO_COSTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(EXISTENCIAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRIMERO)
                    .addComponent(ANTERIOR)
                    .addComponent(SIGUIENTE)
                    .addComponent(ULTIMO)
                    .addComponent(EDITAR)
                    .addComponent(NUEVO)
                    .addComponent(CONFIRMAR)
                    .addComponent(CANCELAR))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void COD_ARTICULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COD_ARTICULOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COD_ARTICULOActionPerformed

    private void PESOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PESOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PESOActionPerformed

    private void EXISTENCIASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXISTENCIASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EXISTENCIASActionPerformed

    private void EDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITARActionPerformed
        try {
            String vCOD_ARTICULO, vARTICULO, vFABRICANTE, vPESO, vCATEGORIA, vPRECIO_VENTA, vPRECIO_COSTE, vEXISTENCIAS;
            
            vCOD_ARTICULO = COD_ARTICULO.getText();
            vARTICULO = ARTICULO.getText();
            vFABRICANTE = FABRICANTE.getText();
            vPESO = PESO.getText();
            vCATEGORIA = CATEGORIA.getText();
            vPRECIO_VENTA = PRECIO_VENTA.getText();
            vPRECIO_COSTE = PRECIO_COSTE.getText();
            vEXISTENCIAS = EXISTENCIAS.getText();
            String url = "jdbc:mysql://localhost:3306/sergiooyono";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);
            Statement s = connection.createStatement();
            String query = "update articulos set ARTICULO='" + vARTICULO + "', FABRICANTE='" + vFABRICANTE + "', PESO='" + vPESO + "', CATEGORIA='" + vCATEGORIA + "', PRECIO_VENTA='" + vPRECIO_VENTA + "', PRECIO_COSTE='" + vPRECIO_COSTE + "', EXISTENCIAS='" + vEXISTENCIAS + "' WHERE COD_ARTICULO='" + vCOD_ARTICULO + "'";
            int resultado = s.executeUpdate(query);
            r.refreshRow();
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EDITARActionPerformed

    private void NUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVOActionPerformed
        // TODO add your handling code here:
        PRIMERO.setVisible(false);
        ANTERIOR.setVisible(false);
        SIGUIENTE.setVisible(false);
        ULTIMO.setVisible(false);
        NUEVO.setVisible(false);
        EDITAR.setVisible(false);
        CONFIRMAR.setVisible(true);
        CANCELAR.setVisible(true);
        COD_ARTICULO.setEditable(true);
        COD_ARTICULO.setText("");
        ARTICULO.setText("");
        FABRICANTE.setText("");
        PESO.setText("");
        CATEGORIA.setText("");
        PRECIO_VENTA.setText("");
        PRECIO_COSTE.setText("");
        EXISTENCIAS.setText("");

    }//GEN-LAST:event_NUEVOActionPerformed

    private void PRIMEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRIMEROActionPerformed
        // TODO add your handling code here:
        try {
            r.first();
            COD_ARTICULO.setText(r.getString("COD_ARTICULO"));
            ARTICULO.setText(r.getString("ARTICULO"));
            FABRICANTE.setText(r.getString("FABRICANTE"));
            PESO.setText(r.getString("PESO"));
            CATEGORIA.setText(r.getString("CATEGORIA"));
            PRECIO_VENTA.setText(r.getString("PRECIO_VENTA"));
            PRECIO_COSTE.setText(r.getString("PRECIO_COSTE"));
            EXISTENCIAS.setText(r.getString("EXISTENCIAS"));
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PRIMEROActionPerformed

    private void ANTERIORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANTERIORActionPerformed
        // TODO add your handling code here:
        try {
            if (r.previous()) {
                COD_ARTICULO.setText(r.getString("COD_ARTICULO"));
                ARTICULO.setText(r.getString("ARTICULO"));
                FABRICANTE.setText(r.getString("FABRICANTE"));
                PESO.setText(r.getString("PESO"));
                CATEGORIA.setText(r.getString("CATEGORIA"));
                PRECIO_VENTA.setText(r.getString("PRECIO_VENTA"));
                PRECIO_COSTE.setText(r.getString("PRECIO_COSTE"));
                EXISTENCIAS.setText(r.getString("EXISTENCIAS"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ANTERIORActionPerformed

    private void SIGUIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGUIENTEActionPerformed
        // TODO add your handling code here:
        try {
            if (r.next()) {
                COD_ARTICULO.setText(r.getString("COD_ARTICULO"));
                ARTICULO.setText(r.getString("ARTICULO"));
                FABRICANTE.setText(r.getString("FABRICANTE"));
                PESO.setText(r.getString("PESO"));
                CATEGORIA.setText(r.getString("CATEGORIA"));
                PRECIO_VENTA.setText(r.getString("PRECIO_VENTA"));
                PRECIO_COSTE.setText(r.getString("PRECIO_COSTE"));
                EXISTENCIAS.setText(r.getString("EXISTENCIAS"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);        // TODO add your handling code here:
        }
    }//GEN-LAST:event_SIGUIENTEActionPerformed

    private void ULTIMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ULTIMOActionPerformed
        // TODO add your handling code here:
        try {
            if (r.last()) {
                COD_ARTICULO.setText(r.getString("COD_ARTICULO"));
                ARTICULO.setText(r.getString("ARTICULO"));
                FABRICANTE.setText(r.getString("FABRICANTE"));
                PESO.setText(r.getString("PESO"));
                CATEGORIA.setText(r.getString("CATEGORIA"));
                PRECIO_VENTA.setText(r.getString("PRECIO_VENTA"));
                PRECIO_COSTE.setText(r.getString("PRECIO_COSTE"));
                EXISTENCIAS.setText(r.getString("EXISTENCIAS"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);        // TODO add your handling code here:
        }
    }//GEN-LAST:event_ULTIMOActionPerformed

    private void CONFIRMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONFIRMARActionPerformed
        // TODO add your handling code here:
        try {
            String vCOD_ARTICULO, vARTICULO, vFABRICANTE, vPESO, vCATEGORIA, vPRECIO_VENTA, vPRECIO_COSTE, vEXISTENCIAS;
            vCOD_ARTICULO = COD_ARTICULO.getText();
            vARTICULO = ARTICULO.getText();
            vFABRICANTE = FABRICANTE.getText();
            vPESO = PESO.getText();
            vCATEGORIA = CATEGORIA.getText();
            vPRECIO_VENTA = PRECIO_VENTA.getText();
            vPRECIO_COSTE = PRECIO_COSTE.getText();
            vEXISTENCIAS = EXISTENCIAS.getText();
            String url = "jdbc:mysql://localhost:3306/sergiooyono";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);
            Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "insert into articulos values ('" + vCOD_ARTICULO+"', '"+ vARTICULO+"', '"+vFABRICANTE+"', '"+vPESO+"', '"+vCATEGORIA+"', '"+vPRECIO_VENTA+"','"+ vPRECIO_COSTE+"','"+vEXISTENCIAS+"')";
            int resultado = s.executeUpdate(query);
            COD_ARTICULO.setEditable(false);
            PRIMERO.setVisible(false);
            ANTERIOR.setVisible(true);
            SIGUIENTE.setVisible(true);
            ULTIMO.setVisible(true);
            NUEVO.setVisible(true);
            EDITAR.setVisible(true);
            CONFIRMAR.setVisible(false);
            CANCELAR.setVisible(false);
            r.refreshRow();
            r.last();

        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_CONFIRMARActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        // TODO add your handling code here:
        try {
            COD_ARTICULO.setEditable(false);
            PRIMERO.setVisible(false);
            ANTERIOR.setVisible(true);
            SIGUIENTE.setVisible(true);
            ULTIMO.setVisible(true);
            NUEVO.setVisible(true);
            EDITAR.setVisible(true);
            CONFIRMAR.setVisible(false);
            CANCELAR.setVisible(false);
            r.refreshRow();
            r.last();
            COD_ARTICULO.setText(r.getString("COD_ARTICULO"));
            ARTICULO.setText(r.getString("ARTICULO"));
            FABRICANTE.setText(r.getString("FABRICANTE"));
            PESO.setText(r.getString("PESO"));
            CATEGORIA.setText(r.getString("CATEGORIA"));
            PRECIO_VENTA.setText(r.getString("PRECIO_VENTA"));
            PRECIO_COSTE.setText(r.getString("PRECIO_COSTE"));
            EXISTENCIAS.setText(r.getString("EXISTENCIAS"));
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CANCELARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Articulos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANTERIOR;
    private javax.swing.JTextField ARTICULO;
    private javax.swing.JButton CANCELAR;
    private javax.swing.JTextField CATEGORIA;
    private javax.swing.JTextField COD_ARTICULO;
    private javax.swing.JButton CONFIRMAR;
    private javax.swing.JButton EDITAR;
    private javax.swing.JTextField EXISTENCIAS;
    private javax.swing.JTextField FABRICANTE;
    private javax.swing.JButton NUEVO;
    private javax.swing.JTextField PESO;
    private javax.swing.JTextField PRECIO_COSTE;
    private javax.swing.JTextField PRECIO_VENTA;
    private javax.swing.JButton PRIMERO;
    private javax.swing.JButton SIGUIENTE;
    private javax.swing.JButton ULTIMO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
