/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author entorno
 */
public class Fabricantes extends javax.swing.JFrame {
    
    static public ResultSet r;
    
    public Fabricantes() throws SQLException {
        initComponents();
        
        CONFIRMAR.setVisible(false);
        CANCELAR.setVisible(false);
        
        String url = "jdbc:mysql://localhost:3306/sergiooyono";
        String user = "root";
        String pass = "";
        Connection connection = DriverManager.getConnection(url, user, pass);
        
        Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String query = "select* from fabricantes";
        r = s.executeQuery(query);
        r.first();
        COD_FABRICANTE.setText(r.getString("COD_FABRICANTE"));
        NOMBRE.setText(r.getString("NOMBRE"));
        PAIS.setText(r.getString("PAIS"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        COD_FABRICANTE = new javax.swing.JTextField();
        NOMBRE = new javax.swing.JTextField();
        PAIS = new javax.swing.JTextField();
        PRIMERO = new javax.swing.JButton();
        ANTERIOR = new javax.swing.JButton();
        SIGUIENTE = new javax.swing.JButton();
        ULTIMO = new javax.swing.JButton();
        EDITAR = new javax.swing.JButton();
        NUEVO = new javax.swing.JButton();
        CONFIRMAR = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("COD_FABRICANTE");

        jLabel2.setText("NOMBRE");

        jLabel3.setText("PAIS");

        COD_FABRICANTE.setEditable(false);
        COD_FABRICANTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COD_FABRICANTEActionPerformed(evt);
            }
        });

        NOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOMBREActionPerformed(evt);
            }
        });

        PAIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAISActionPerformed(evt);
            }
        });

        PRIMERO.setText("PRIMERO");
        PRIMERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRIMEROActionPerformed(evt);
            }
        });

        ANTERIOR.setText("ANTERIOR");
        ANTERIOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANTERIORActionPerformed(evt);
            }
        });

        SIGUIENTE.setText("SIGUIENTE");
        SIGUIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIGUIENTEActionPerformed(evt);
            }
        });

        ULTIMO.setText("ULTIMO");
        ULTIMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ULTIMOActionPerformed(evt);
            }
        });

        EDITAR.setText("EDITAR");
        EDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITARActionPerformed(evt);
            }
        });

        NUEVO.setText("NUEVO");
        NUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVOActionPerformed(evt);
            }
        });

        CONFIRMAR.setText("CONFIRMAR");
        CONFIRMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONFIRMARActionPerformed(evt);
            }
        });

        CANCELAR.setText("CANCELAR");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NOMBRE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(PAIS, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(COD_FABRICANTE, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(167, 167, 167))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PRIMERO)
                .addGap(26, 26, 26)
                .addComponent(ANTERIOR)
                .addGap(18, 18, 18)
                .addComponent(SIGUIENTE)
                .addGap(18, 18, 18)
                .addComponent(ULTIMO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(EDITAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NUEVO)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(CONFIRMAR)
                .addGap(120, 120, 120)
                .addComponent(CANCELAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(COD_FABRICANTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PAIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CONFIRMAR)
                    .addComponent(CANCELAR))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRIMERO)
                    .addComponent(ANTERIOR)
                    .addComponent(SIGUIENTE)
                    .addComponent(ULTIMO)
                    .addComponent(EDITAR)
                    .addComponent(NUEVO))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void COD_FABRICANTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COD_FABRICANTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COD_FABRICANTEActionPerformed

    private void NOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOMBREActionPerformed

    private void PAISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PAISActionPerformed

    private void PRIMEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRIMEROActionPerformed
        try {
            r.first();
            COD_FABRICANTE.setText(r.getString("COD_FABRICANTE"));
            NOMBRE.setText(r.getString("NOMBRE"));
            PAIS.setText(r.getString("PAIS"));
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PRIMEROActionPerformed

    private void ANTERIORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANTERIORActionPerformed
        try {
            if (r.previous()) {
                COD_FABRICANTE.setText(r.getString("COD_FABRICANTE"));
                NOMBRE.setText(r.getString("NOMBRE"));
                PAIS.setText(r.getString("PAIS"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
    }//GEN-LAST:event_ANTERIORActionPerformed
    }
    private void SIGUIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGUIENTEActionPerformed
        try {
            if (r.next()) {
                COD_FABRICANTE.setText(r.getString("COD_FABRICANTE"));
                NOMBRE.setText(r.getString("NOMBRE"));
                PAIS.setText(r.getString("PAIS"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);        // TODO add your handling code here:
    }//GEN-LAST:event_SIGUIENTEActionPerformed
    }
    private void ULTIMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ULTIMOActionPerformed
        try {
            if (r.last()) {
                COD_FABRICANTE.setText(r.getString("COD_FABRICANTE"));
                NOMBRE.setText(r.getString("NOMBRE"));
                PAIS.setText(r.getString("PAIS"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ULTIMOActionPerformed

    private void NUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVOActionPerformed
        // TODO add your handling code here:
        PRIMERO.setVisible(false);
        ANTERIOR.setVisible(false);
        SIGUIENTE.setVisible(false);
        ULTIMO.setVisible(false);
        NUEVO.setVisible(false);
        EDITAR.setVisible(false);
        CONFIRMAR.setVisible(true);
        CANCELAR.setVisible(true);
        COD_FABRICANTE.setEditable(true);
        COD_FABRICANTE.setText("");
        NOMBRE.setText("");
        PAIS.setText("");
    }//GEN-LAST:event_NUEVOActionPerformed

    private void EDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITARActionPerformed
        try {
            String vCOD_FABRICANTE, vNOMBRE, vPAIS;
            vCOD_FABRICANTE = COD_FABRICANTE.getText();
            vNOMBRE = NOMBRE.getText();
            vPAIS = PAIS.getText();
            String url = "jdbc:mysql://localhost:3306/sergiooyono";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);
            Statement s = connection.createStatement();
            String query = "update fabricantes set NOMBRE='" + vNOMBRE + "', PAIS='" + vPAIS + "' WHERE COD_FABRICANTE='" + vCOD_FABRICANTE + "'";
            int resultado = s.executeUpdate(query);
            r.refreshRow();
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EDITARActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        // TODO add your handling code here:
        try {
            COD_FABRICANTE.setEditable(false);
            PRIMERO.setVisible(true);
            ANTERIOR.setVisible(true);
            SIGUIENTE.setVisible(true);
            ULTIMO.setVisible(true);
            NUEVO.setVisible(true);
            EDITAR.setVisible(true);
            CONFIRMAR.setVisible(false);
            CANCELAR.setVisible(false);
            r.refreshRow();
            r.last();
            COD_FABRICANTE.setText(r.getString("COD_FABRICANTE"));
            NOMBRE.setText(r.getString("NOMBRE"));
            PAIS.setText(r.getString("PAIS"));
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CANCELARActionPerformed

    private void CONFIRMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONFIRMARActionPerformed
        // TODO add your handling code here:
        try {
            String vCOD_FABRICANTE, vNOMBRE, vPAIS; 
            vCOD_FABRICANTE = COD_FABRICANTE.getText();
            vNOMBRE = NOMBRE.getText();
            vPAIS = PAIS.getText();
            String url = "jdbc:mysql://localhost:3306/sergiooyono";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);
            Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "insert into  fabricantes values ('" + vCOD_FABRICANTE + "', '" + vNOMBRE + "', '" + vPAIS + "')";
            int resultado = s.executeUpdate(query);
            COD_FABRICANTE.setEditable(false);
            PRIMERO.setVisible(true);
            ANTERIOR.setVisible(true);
            SIGUIENTE.setVisible(true);
            ULTIMO.setVisible(true);
            NUEVO.setVisible(true);
            EDITAR.setVisible(true);
            CONFIRMAR.setVisible(false);
            CANCELAR.setVisible(false);
            
            
            s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE); //actualizamos
            query = "select* from articulos";
            r = s.executeQuery(query);
            r.last();
            
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
    }//GEN-LAST:event_CONFIRMARActionPerformed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fabricantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Fabricantes().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Fabricantes.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANTERIOR;
    private javax.swing.JButton CANCELAR;
    private javax.swing.JTextField COD_FABRICANTE;
    private javax.swing.JButton CONFIRMAR;
    private javax.swing.JButton EDITAR;
    private javax.swing.JTextField NOMBRE;
    private javax.swing.JButton NUEVO;
    private javax.swing.JTextField PAIS;
    private javax.swing.JButton PRIMERO;
    private javax.swing.JButton SIGUIENTE;
    private javax.swing.JButton ULTIMO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
